[http]
  [http.middlewares]
    [http.middlewares.static-headers]
      [http.middlewares.static-headers.headers]
        browserXssFilter = true
        contentTypeNosniff = true
        frameDeny = true
        [http.middlewares.static-headers.headers.customResponseHeaders]
          Cache-Control = "public, max-age=31536000"

  [http.routers]
    [http.routers.django-static]
      rule = "Host(`api.futurprive.com`) && PathPrefix(`/static/`)"
      service = "django"
      middlewares = ["static-headers"]
      entryPoints = ["websecure"]
      [http.routers.django-static.tls]
        certResolver = "leresolver"